definitions:
  assets.MessageResponse:
    properties:
      message:
        type: string
    type: object
  assets.NewAssetRequest:
    properties:
      address:
        type: string
      balance:
        type: number
      name:
        type: string
      network:
        type: string
      symbol:
        type: string
      wallet_id:
        type: integer
    required:
    - address
    - balance
    - name
    - network
    - symbol
    - wallet_id
    type: object
  auth.AccessTokenRequest:
    properties:
      refreshToken:
        example: badbunybabybebe
        type: string
    required:
    - refreshToken
    type: object
  auth.DataUserAuthenticated:
    properties:
      email:
        example: some@mail.com
        type: string
      firstName:
        example: John
        type: string
      id:
        example: 123
        type: integer
      lastName:
        example: Doe
        type: string
      userName:
        example: UserName
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        example: mail@mail.com
        type: string
      password:
        example: Password123
        type: string
    required:
    - email
    - password
    type: object
  controllers.MessageResponse:
    properties:
      message:
        type: string
    type: object
  tennet_gethired_application_usecases_assets.PaginationResultAsset:
    properties:
      current:
        type: integer
      data:
        items:
          $ref: '#/definitions/tennet_gethired_domain_assets.Asset'
        type: array
      limit:
        type: integer
      nextCursor:
        type: integer
      numPages:
        type: integer
      prevCursor:
        type: integer
      total:
        type: integer
    type: object
  tennet_gethired_domain_assets.Asset:
    properties:
      address:
        type: string
      balance:
        type: number
      id:
        type: integer
      name:
        type: string
      network:
        type: string
      symbol:
        type: string
      wallet_id:
        type: integer
    type: object
  user.MessageResponse:
    properties:
      message:
        type: string
    type: object
  user.NewUserRequest:
    properties:
      email:
        example: mail@mail.com
        type: string
      firstName:
        example: John
        type: string
      lastName:
        example: Doe
        type: string
      password:
        example: Password123
        type: string
      username:
        example: someUser
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    - username
    type: object
  user.ResponseUser:
    properties:
      createdAt:
        example: "2021-02-24 20:19:39"
        type: string
      email:
        example: some@mail.com
        type: string
      firstName:
        example: John
        type: string
      id:
        example: 1099
        type: integer
      lastName:
        example: Doe
        type: string
      updatedAt:
        example: "2021-02-24 20:19:39"
        type: string
      user:
        example: BossonH
        type: string
    type: object
info:
  contact: {}
paths:
  /asset:
    get:
      description: Get all Assets on the system
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tennet_gethired_application_usecases_assets.PaginationResultAsset'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/assets.MessageResponse'
      summary: Get all Assets
      tags:
      - asset
    post:
      consumes:
      - application/json
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/assets.NewAssetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tennet_gethired_domain_assets.Asset'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/assets.MessageResponse'
      summary: Create New Asset
      tags:
      - asset
  /asset/{asset_id}:
    delete:
      parameters:
      - description: id of asset
        in: path
        name: asset_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tennet_gethired_domain_assets.Asset'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/assets.MessageResponse'
      summary: Get assets by ID
      tags:
      - asset
    get:
      parameters:
      - description: id of asset
        in: path
        name: asset_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tennet_gethired_domain_assets.Asset'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/assets.MessageResponse'
      summary: Get assets by ID
      tags:
      - asset
    patch:
      parameters:
      - description: id of asset
        in: path
        name: asset_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tennet_gethired_domain_assets.Asset'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/assets.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/assets.MessageResponse'
      summary: Get assets by ID
      tags:
      - asset
  /auth/access-token:
    post:
      description: Auth user by email and password
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.AccessTokenRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.DataUserAuthenticated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      summary: GetAccessTokenByRefreshToken UserName
      tags:
      - auth
  /auth/login:
    post:
      description: Auth user by email and password
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.DataUserAuthenticated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      summary: Login UserName
      tags:
      - auth
  /user:
    post:
      consumes:
      - application/json
      description: Create new user on the system
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.NewUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New UserName
      tags:
      - user
  /user/{user_id}:
    delete:
      description: Get Users by ID on the system
      parameters:
      - description: id of user
        in: path
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get users by ID
      tags:
      - user
    get:
      description: Get Users by ID on the system
      parameters:
      - description: id of user
        in: path
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get users by ID
      tags:
      - user
    patch:
      description: Get Users by ID on the system
      parameters:
      - description: id of user
        in: path
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/user.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get users by ID
      tags:
      - user
swagger: "2.0"
